### ISSUE TITLE
Zip feature not working on android

### ISSUE THREAD

**Issue by Daniele-rolli** [Jun-Murakami/capa-zip#1]
Hey there,

First off, I just want to say this plugin is amazing!

I’ve run into an issue on Android, though. The plugin works perfectly on iOS, but on Android, it seems like it can’t find the folder, even though it’s definitely there. Since iOS has no issues, I’m wondering if something might not be working quite right in the Android implementation.

Here’s the relevant log snippet:
```
2025-01-31 20:01:46.478  2702-2702  Capacitor/Plugin        beaver.notes.pocket                  V  To native (Capacitor plugin): callbackId: 83127104, pluginId: Zip, methodName: zip
2025-01-31 20:01:46.479  2702-2702  Capacitor               beaver.notes.pocket                  V  callback: 83127104, pluginId: Zip, methodName: zip, methodData: {"sourcePath":"export\/Beaver Notes 2025-01-31","destinationPath":"export\/Beaver Notes 2025-01-31.zip"}
2025-01-31 20:01:46.479  2702-3257  ZipPlugin               beaver.notes.pocket                  E  Source path does not exist: export/Beaver Notes 2025-01-31
2025-01-31 20:01:46.479  2702-3257  Capacitor               beaver.notes.pocket                  D  Sending plugin error: {"save":false,"callbackId":"83127104","pluginId":"Zip","methodName":"zip","success":false,"error":{"message":"Source path does not exist"}}
```
It looks like it’s failing with "Source path does not exist," even though the folder is there. Any idea what might be going on?

**Comment by Jun-Murakami** [comment]
Thank you for reporting this issue and for your kind words about the plugin!

I've identified and fixed the issue. The problem was with how relative paths were being resolved on Android. While iOS was correctly resolving paths relative to the app's documents directory, Android needed explicit path resolution to the external files directory.

### What's been fixed
- Updated Android path resolution to properly handle relative paths using `getExternalFilesDir(null)`
- Added more comprehensive path resolution tests
- Enhanced the example app with detailed path logging for debugging
- Added `removeAllListeners()` method for proper cleanup of progress event listeners

### Testing the fix
I've just published version 7.0.1 with this fix. You can try it by updating the plugin:

**Comment by Daniele-rolli** [comment]
Thanks for the prompt reply. I've updated to 7.0.1, but I'm still experiencing issues with Capacitor. Normally, when writing a file, you can specify the directory `e.g Directory.Data`, which means it should be stored under `/data/data/beaver.notes.pocket/files/export/Beaver Notes 2025-02-04`. However, the plugin is looking for it inside `storage/emulated/0/Android/data/beaver.notes.pocket/files/export/Beaver Notes 2025-02-04`. Notice the missing second `data` folder. Thanks again!

**Comment by Jun-Murakami** [comment]
Thank you for the detailed feedback. I see the issue now - there was a misunderstanding about the correct directory mapping for `Directory.Data`.

The plugin was using Android's external files directory (`getExternalFilesDir()`), when it should have been using the internal files directory (`getFilesDir()`). This explains why the paths weren't matching up with Capacitor's `Directory.Data`.

I've just pushed version 7.0.3 that fixes this directory mapping issue. Now it should correctly resolve to:
`/data/data/[package]/files/` instead of `/storage/emulated/0/Android/data/[package]/files/`

Could you please try updating to 7.0.3?
npm install capa-zip@latest

The paths should now match exactly with what you get from Capacitor's Directory.Data. Let me know if you're still experiencing any issues.

**Comment by Daniele-rolli** [comment]
Wonderful! Thanks! It works flawlessly, amazing job and an amazing plugin. Thanks again! You really saved my project, [Beaver Pocket](https://github.com/Beaver-Notes/Beaver-pocket). Without this plugin, I would be at a loss.
